import {useEffect,useMemo,useState} from 'react';
import {concepts,lessonSections,conceptGroups} from './concepts';
import {project,nodes,scaling,course,requestFlow} from './projects/all-media-downloader';
import {futureProjectSlots} from './projects';
import {incidents} from './projects/all-media-downloader/incidents';
import {questions} from './interview/questions';
import {loadState,saveState,setCompleted,toggleBookmark,percentFor,type LearningState} from './state';
import {gigabytesPerDay,littleLaw,mbps,percentile} from './simulations/math';
import {Icon,Badge,SectionTitle} from './components/ui';
import {knowledgeMap} from './data/knowledge-map';
import type {Lesson} from './types';

type Page='home'|'project'|'concepts'|'interview'|'incidents'|'simulators'|'rebuild'|'portfolio';

export default function App(){
 const [page,setPage]=useState<Page>('home');
 const [state,setState]=useState<LearningState>(()=>loadState());
 const [activeLesson,setActiveLesson]=useState<Lesson>(concepts[0]);
 const [selectedNode,setSelectedNode]=useState<string|null>(null);
 const [levelTab,setLevelTab]=useState<'simple'|'technical'|'interview'>('simple');
 const [toast,setToast]=useState('');
 const [theme,setTheme]=useState<'light'|'dark'>(()=>{const saved=window.localStorage.getItem('pl-theme');if(saved==='light'||saved==='dark')return saved;return typeof window.matchMedia==='function'&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'});
 useEffect(()=>saveState(state),[state]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;const meta=document.querySelector<HTMLMetaElement>('meta[name="theme-color"]');if(meta)meta.content=theme==='dark'?'#0b0b0c':'#fafafa'},[theme]);
 function notify(text:string){setToast(text);window.setTimeout(()=>setToast(''),2300)}
 function openLesson(id:string){const l=concepts.find(x=>x.id===id);if(l){window.localStorage.setItem('project-learnings.last-lesson.v1',id);setActiveLesson(l);setPage('concepts');setLevelTab('simple');setSelectedNode(null)}}
 const groups:{label:string;items:[Page,string,string][]}[]=[
  {label:'LEARN',items:[['home','Overview','⌂'],['project','Projects','▧'],['concepts','Knowledge map','⌘']]},
  {label:'PRACTICE',items:[['interview','Interview gym','?'],['incidents','Incident lab','!'],['simulators','Simulations','↗'],['rebuild','Final boss','◇']]},
  {label:'EXPLAIN',items:[['portfolio','Project story','↗']]},
 ];
 const pageLabel=groups.flatMap(g=>g.items).find(x=>x[0]===page)?.[1]||'Overview';
 return <div className="app-shell"><aside className="sidebar">
  <button className="brand" onClick={()=>setPage('home')} aria-label="Project Learnings home"><span className="brand-mark">P<span>·</span>L</span><span>Project<br/><b>Learnings</b></span></button>
  <nav aria-label="Main navigation">{groups.map(g=><div className="nav-group" key={g.label}><div className="nav-group-label">{g.label}</div>{g.items.map(([id,label,icon])=><button key={id} className={'nav-item '+(page===id?'active':'')} aria-current={page===id?'page':undefined} onClick={()=>setPage(id)}><Icon>{icon}</Icon><span>{label}</span>{id==='interview'&&<span className="nav-count">100</span>}</button>)}</div>)}</nav>
  <div className="sidebar-bottom"><div className="mini-progress"><div className="sidebar-label">CASE STUDY PROGRESS</div><strong>{percentFor(state,concepts.map(x=>x.id))}%</strong><div className="progress-track"><i style={{width:percentFor(state,concepts.map(x=>x.id))+'%'}}/></div><small>{state.completed.filter(x=>x.startsWith('all-media-downloader:')).length} lessons completed</small></div><div className="privacy"><span className="green-dot"/>Saved on this device</div></div>
 </aside><main className="main-area">
  <header className="topbar"><div className="breadcrumb"><span>Project Learnings</span><span aria-hidden="true">/</span><b>{pageLabel}</b></div><div className="top-right"><span className="online"><i/> Local learning mode</span><button className="theme-toggle" type="button" aria-label={'Switch to '+(theme==='dark'?'light':'dark')+' mode'} title={'Switch to '+(theme==='dark'?'light':'dark')+' mode'} onClick={()=>{const next=theme==='dark'?'light':'dark';window.localStorage.setItem('pl-theme',next);setTheme(next)}}><span aria-hidden="true">{theme==='dark'?'☾':'☼'}</span><b>Switch to {theme==='dark'?'light':'dark'} mode</b></button></div></header>
  <div className="page-content">{page==='home'&&<Home state={state} setPage={setPage} openLesson={openLesson}/>}{page==='project'&&<ProjectPage state={state} onNode={id=>setSelectedNode(id)} openLesson={openLesson}/>}{page==='concepts'&&<ConceptPage state={state} setState={setState} lesson={activeLesson} setLesson={setActiveLesson} tab={levelTab} setTab={setLevelTab} notify={notify}/>}{page==='interview'&&<InterviewPage state={state} setState={setState}/>}{page==='incidents'&&<IncidentPage/>}{page==='simulators'&&<Simulators/>}{page==='rebuild'&&<RebuildBoss/>}{page==='portfolio'&&<Portfolio/>}</div>
  <footer className="footer">Built from real projects <span>·</span> Your learning progress stays in this browser</footer>
 </main>{selectedNode&&<NodeDrawer id={selectedNode} close={()=>setSelectedNode(null)} openLesson={openLesson}/>}{toast&&<div className="toast" role="status">{toast}</div>}</div>;
}

function Home({state,setPage,openLesson}:{state:LearningState;setPage:(p:Page)=>void;openLesson:(s:string)=>void}){
 const ordered=course.flatMap(level=>level.conceptIds);
 const nextId=ordered.find(id=>!state.completed.includes('all-media-downloader:'+id))||concepts[0].id;
 const remembered=window.localStorage.getItem('project-learnings.last-lesson.v1');
 const current=concepts.find(c=>c.id===remembered)||concepts.find(c=>c.id===nextId)||concepts[0];
 const level=course.find(c=>c.conceptIds.includes(current.id));
 const done=concepts.filter(c=>state.completed.includes('all-media-downloader:'+c.id)).length;
 const read=state.completed.includes('all-media-downloader:'+current.id);
 return <div className="home-page">
  <section className="home-intro"><div className="eyebrow">A PROJECT-BASED ENGINEERING LEARNING SPACE</div><h1>Project Learnings</h1><p>Learn software engineering through systems you built. Connect code to production behavior, computer science and interview reasoning.</p></section>
  <section className="continue-card" aria-labelledby="continue-title"><div><div className="eyebrow">{remembered?'CONTINUE YOUR STUDY':'RECOMMENDED NEXT LESSON'} · ALL MEDIA DOWNLOADER</div><h2 id="continue-title">{current.title}</h2><p>{current.summary}</p><div className="continue-meta">Level {String((level?.level??0)+1).padStart(2,'0')} of 24 · {read?'Read before':'Next in your path'}</div></div><div className="continue-actions"><button className="button" onClick={()=>openLesson(current.id)}>{remembered?'Continue learning':'Start here'} <span aria-hidden="true">→</span></button><button className="subtle-button" onClick={()=>setPage('project')}>View project path</button></div></section>
  <section className="home-section"><div className="home-section-title"><div><h2>Choose a study mode</h2><p>Follow the system, study a concept or practice your reasoning.</p></div></div><div className="explore-links"><button onClick={()=>setPage('project')}><b>Projects</b><span>Trace a real request through its architecture.</span></button><button onClick={()=>setPage('concepts')}><b>Concepts</b><span>Build reusable understanding by topic.</span></button><button onClick={()=>setPage('interview')}><b>Interview practice</b><span>Recall first, then reveal the answer.</span></button><button onClick={()=>setPage('incidents')}><b>Engineering labs</b><span>Investigate incidents and assumptions.</span></button></div></section>
  <section className="home-section"><div className="home-section-title"><div><h2>Your learning progress</h2><p>Completion tracks what you have read, not mastery.</p></div><button className="text-button" onClick={()=>setPage('concepts')}>Review concepts →</button></div><div className="progress-summary"><strong>{done} of {concepts.length} lessons read</strong><div className="progress-track" role="progressbar" aria-label="Lessons read" aria-valuemin={0} aria-valuemax={concepts.length} aria-valuenow={done}><i style={{width:Math.round(done/concepts.length*100)+'%'}}/></div><span>{Math.round(done/concepts.length*100)}%</span></div></section>
  <div className="future-projects"><b>Designed to grow across projects.</b> {futureProjectSlots.map(x=>x.title).join(' · ')} are reserved for future case studies.</div>
 </div>;
}

function ProjectPage({state,onNode,openLesson}:{state:LearningState;onNode:(id:string)=>void;openLesson:(id:string)=>void}){
  const [step,setStep]=useState(-1);const [tab,setTab]=useState<'map'|'lifecycle'|'course'|'evidence'>('map');
  const mainNodes=['user','telegram-api','handlers','validation','metadata','queue','executor','ytdlp','disk','uploadgate','stream','delivery'];
  const support=['deno','ffmpeg','sqlite','json','warp','systemd','cgroups','health','kuma'];
  const order=requestFlow;
  const stepNodeIds=['user','telegram-api','handlers','validation','metadata','metadata','queue','executor','ytdlp','deno','disk','uploadgate','stream','delivery','user'];
  const flowNodes=mainNodes.map(id=>nodes.find(n=>n.id===id)!);
  const currentLevel=course.find(c=>!c.conceptIds.every(id=>state.completed.includes('all-media-downloader:'+id)))?.level??course[course.length-1].level;
  return <>
    <div className="project-hero"><div><div className="eyebrow">PROJECT 01 · PRODUCTION CASE STUDY</div><h1>All Media<br/><em>Downloader</em></h1><p>{project.oneLiner}</p><div className="badges">{project.badges.map(x=><Badge key={x}>{x}</Badge>)}</div></div><div className="project-stamp"><span>APPLICATION BASELINE</span><b>v1.0.0</b><code>830f351</code><small>Docs freeze 374acfd<br/>describes this baseline</small></div></div>
    <div className="tabbar">{[['map','Architecture map'],['lifecycle','Follow a request'],['course','Learning roadmap'],['evidence','Evidence & constraints']].map(([id,label])=><button className={tab===id?'selected':''} key={id} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</div>
    {tab==='map'&&<><div className="map-intro"><div><div className="eyebrow">CLICK ANY COMPONENT</div><h2>One bot. Many boundaries.</h2><p>Each node opens its role, CS connection, code location, resource cost and failure mode.</p></div><div className="map-legend"><span><i className="legend-app"/>App</span><span><i className="legend-external"/>External</span><span><i className="legend-ops"/>Operations</span></div></div><div className="architecture-board"><div className="main-flow">{flowNodes.map((n,i)=><div className="flow-item" key={n.id}><button className={`arch-node ${n.kind}`} onClick={()=>onNode(n.id)}><span className="node-num">{String(i+1).padStart(2,'0')}</span><b>{n.label}</b><small>{n.subtitle}</small><span className="node-open">↗</span></button>{i<flowNodes.length-1&&<div className="flow-arrow"><span>↓</span></div>}</div>)}</div><div className="support-panel"><div className="eyebrow">SUPPORTING SYSTEMS · CLICK TO EXPLORE</div><div className="support-grid">{support.map(id=>{const n=nodes.find(n=>n.id===id)!;return <button key={id} onClick={()=>onNode(id)} className={`support-node ${n.kind}`}><span>{n.kind==='ops'?'⌘':n.kind==='storage'?'▤':n.kind==='dependency'?'↗':'◇'}</span><b>{n.label}</b><small>{n.subtitle}</small><i>↗</i></button>})}</div></div><div className="board-caption"><span>CODE BASELINE <b>830f351</b></span><span>DOCS-ONLY FREEZE <b>374acfd</b></span><span>Project-specific evidence is labeled [C] or [M]</span></div></div><div className="map-footnote"><b>Production topology:</b> bot under host systemd; Kuma and bgutil in containers; WARP is a host service when configured. The local Compose bot is a separate supported topology.</div></>}
    {tab==='lifecycle'&&<div className="panel lifecycle-panel"><div className="panel-head"><div><div className="eyebrow">INTERACTIVE REQUEST TRACE</div><h2>Follow one request</h2><p className="muted">Advance the same job across each boundary. Tap a step to open its lesson.</p></div><button className="button green-button" onClick={()=>setStep(step>=order.length-1?-1:step+1)}>{step<0?'Start the request':step>=order.length-1?'Start again':'Next step →'}</button></div><div className="request-track">{order.map((label,i)=>{const n=nodes.find(x=>x.id===stepNodeIds[i]);return <div className={`request-step ${i<=step?'reached':''} ${i===step?'current':''}`} key={`${label}-${i}`}><button onClick={()=>n&&onNode(n.id)}><span>{String(i+1).padStart(2,'0')}</span><b>{label}</b><small>{i===step?'Now processing':i<step?'Complete':i===step+1?'Next boundary':'Waiting'}</small></button>{i<order.length-1&&<i className={i<step?'done':''}/>}</div>})}</div><div className="callout"><b>Boundary check</b><span>A user-facing success depends on external services and local resource limits, not only handler code. Timeouts bound how long this process waits; they cannot undo a remote side effect.</span></div></div>}
    {tab==='course'&&<><SectionTitle eyebrow="24 LEVELS · BUILD IN ORDER" title="Learning roadmap" description="Start with the CS you know, then assemble it into production and system-design reasoning."/><div className="roadmap">{course.map(c=><div className={'roadmap-level '+(c.level===currentLevel?'current':'')} key={c.level}><div className="level-number">{String(c.level+1).padStart(2,'0')}</div><div className="level-body"><div className="eyebrow">LEVEL {c.level}</div><h3>{c.title}</h3><p>{c.description}</p><div className="concept-chips">{c.conceptIds.map(id=>{const l=concepts.find(c=>c.id===id)!;return <button key={id} onClick={()=>openLesson(id)}>{l.title} <span>↗</span></button>})}</div></div><div className="level-status">{c.conceptIds.every(id=>state.completed.includes(`all-media-downloader:${id}`))?<span className="status-done">Read ✓</span>:c.level===currentLevel?<span className="status-current">Suggested next</span>:<span>Available</span>}</div></div>)}</div></>}
    {tab==='evidence'&&<><SectionTitle eyebrow="SOURCE PROJECT SNAPSHOT" title="Facts before conclusions" description="The code and tests describe current behavior. Historical measurements are labeled and their limits stay visible."/><div className="evidence-grid">{project.constraints.map(([label,desc])=><div className="evidence-card" key={label}><div className="eyebrow">{label}</div><p>{desc}</p></div>)}</div><div className="panel"><div className="panel-head"><div><div className="eyebrow">HISTORICAL 24-HOUR COMPARISON</div><h2>Observed, not attributed</h2></div><Badge>[M] · baseline vs trial</Badge></div><div className="metric-table">{project.metrics.map(m=><div className="metric-row" key={m.name}><b>{m.name}</b><span>{m.baseline}</span><i>→</i><span>{m.trial}</span><small>{m.evidence}</small></div>)}</div><p className="muted">Multiple settings changed and CPU steal changed. This comparison does not prove a single change caused the differences. Raw measurement files are not included in this learning repository; see source project docs for the summarized historical evidence.</p></div></>}
  </>;
}

function NodeDrawer({id,close,openLesson}:{id:string;close:()=>void;openLesson:(id:string)=>void}){
 const node=nodes.find(n=>n.id===id)!;const lesson=concepts.find(c=>c.id===node.lesson)!;useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')close()};window.addEventListener('keydown',onKey);return ()=>window.removeEventListener('keydown',onKey)},[close]);
 return <div className="drawer-backdrop" onClick={close}><aside className="node-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title" onClick={e=>e.stopPropagation()}><button className="close-button" autoFocus aria-label="Close component details" onClick={close}>×</button><div className="eyebrow">ARCHITECTURE COMPONENT · {node.kind}</div><h2 id="drawer-title">{node.label}</h2><p className="muted">{node.subtitle}</p>
  <section className="drawer-section"><h3>What it does</h3><p>{lesson.technical}</p></section><section className="drawer-section"><h3>Why it exists</h3><p>{lesson.why}</p></section><section className="drawer-section"><h3>Connect to OS / CN / DBMS</h3><p>{lesson.cs}</p></section>
  <div className="drawer-pair"><div><small>RESOURCE</small><b>{lesson.resource}</b></div><div><small>FAILURE MODE</small><b>{lesson.failure}</b></div><div><small>PROTECTION</small><b>{lesson.protection}</b></div><div><small>SCALING QUESTION</small><b>{lesson.scale}</b></div></div>
  <details className="lesson-details"><summary>Code location</summary><p>{lesson.location}</p><pre className="code-snippet"><code>{lesson.snippet}</code></pre></details><section className="drawer-section interview-quote"><h3>Interview prompt</h3><p>{lesson.followup}</p></section><button className="button full-button" onClick={()=>openLesson(lesson.id)}>Study this concept →</button>
 </aside></div>;
}

function ConceptPage({state,setState,lesson,setLesson,tab,setTab,notify}:{state:LearningState;setState:(x:LearningState)=>void;lesson:Lesson;setLesson:(x:Lesson)=>void;tab:'simple'|'technical'|'interview';setTab:(x:'simple'|'technical'|'interview')=>void;notify:(s:string)=>void}){
 const [filter,setFilter]=useState('All');const [query,setQuery]=useState('');const [quiz,setQuiz]=useState(false);const [answered,setAnswered]=useState<number|null>(null);const [qIndex,setQIndex]=useState(0);
 const [application,setApplication]=useState(()=>window.localStorage.getItem('project-learnings.apply.v1:'+lesson.id)||'');
 useEffect(()=>setApplication(window.localStorage.getItem('project-learnings.apply.v1:'+lesson.id)||''),[lesson.id]);
 const groups=['All',...conceptGroups];const visible=concepts.filter(c=>(filter==='All'||c.group===filter)&&c.title.toLowerCase().includes(query.toLowerCase()));
 const isDone=state.completed.includes('all-media-downloader:'+lesson.id);const isBookmarked=state.bookmarks.includes(lesson.id);
 const quizItems=[
  {q:'Seven people request the same uncached URL at nearly the same time. What should happen?',a:['Seven extractions run concurrently','One extraction runs and the other callers join','A SQLite transaction serializes seven downloads'],correct:1,why:'The in-flight future coalesces current work. The cache helps later requests after a result exists.'},
  {q:'Two Telegram uploads already use both upload slots. Should a completed third job keep its download slot while waiting?',a:['Yes, to preserve ordering','No; release download capacity and wait at UploadGate','Start a second bot process'],correct:1,why:'Download and upload are separate stages; waiting for Telegram should not occupy scarce download capacity.'},
  {q:'A coroutine times out while its ThreadPoolExecutor function is still blocked. What is true?',a:['The worker thread is forcibly killed','The await ended, but the callable may keep running','The OS rolls back its network request'],correct:1,why:'Cancelling a Future cannot safely terminate an already-running arbitrary thread.'},
  {q:'A host has nonzero swap used but low swap-in, low PSI and stable latency. Is that automatically an incident?',a:['Yes, any swap use is failure','No; occupancy alone is not active pressure','Disable swap immediately'],correct:1,why:'Swap occupancy can be a stock of inactive pages. Correlate active paging, PSI and user latency.'},
  {q:'What is the best reason to add Redis/Celery?',a:['A resume needs more technologies','Measured need for durable cross-process work that a local queue cannot meet','A traffic multiplier is large'],correct:1,why:'Name the job durability, throughput or availability requirement and its operational trade-off.'}
 ];
 const submitQuiz=(ans:number)=>{setAnswered(ans);const key=lesson.id;const prev=state.quiz[key]||{correct:0,total:0};setState({...state,quiz:{...state.quiz,[key]:{correct:prev.correct+(ans===quizItems[qIndex].correct?1:0),total:prev.total+1}}})};
 const saveApplication=(value:string)=>{setApplication(value);window.localStorage.setItem('project-learnings.apply.v1:'+lesson.id,value)};
 const whySections=lessonSections.slice(4,8);const interviewSections=lessonSections.slice(8,10);
 return <div className="concept-layout"><aside className="concept-sidebar" aria-label="Concept library"><div className="eyebrow">SHARED CONCEPT LIBRARY</div><details className="concept-map-preview"><summary>See how CS connects to production</summary><div className="knowledge-stack">{knowledgeMap.map((x,i)=><button key={x.label} onClick={()=>{const next=concepts.find(c=>c.id===x.concept);if(next){setLesson(next);setTab('simple');setQuiz(false);setAnswered(null);window.localStorage.setItem('project-learnings.last-lesson.v1',next.id)}}}><span>{String(i+1).padStart(2,'0')}</span>{x.label}<b aria-hidden="true">↓</b></button>)}</div></details><input className="search-input"  value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a concept…" aria-label="Find a concept"/><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter concepts by area">{groups.map(g=><option key={g}>{g}</option>)}</select><div className="concept-list">{visible.map(c=><button aria-current={lesson.id===c.id?'page':undefined} className={lesson.id===c.id?'current':''} key={c.id} onClick={()=>{setLesson(c);setQuiz(false);setAnswered(null);window.localStorage.setItem('project-learnings.last-lesson.v1',c.id)}}><span className="concept-dot"/><span>{c.title}</span>{state.completed.includes('all-media-downloader:'+c.id)&&<b aria-label="Read">✓</b>}</button>)}</div><div className="library-note">Progress stays in this browser. Lessons connect reusable ideas to verified project examples.</div></aside>
  <article className="lesson-area"><header className="lesson-head"><div className="eyebrow">{lesson.group} · LEVEL {lesson.level+1}</div><div className="lesson-head-row"><div><h1>{lesson.title}</h1><p>{lesson.summary}</p></div><button className={'bookmark '+(isBookmarked?'saved':'')} aria-pressed={isBookmarked} onClick={()=>setState(toggleBookmark(state,lesson.id))}>{isBookmarked?'★ Saved':'☆ Bookmark'}</button></div><div className="lesson-controls"><div className="segmented" role="tablist" aria-label="Explanation level">{(['simple','technical','interview'] as const).map(x=><button role="tab" aria-selected={tab===x} key={x} className={tab===x?'on':''} onClick={()=>setTab(x)}>{x==='simple'?'Simple':x==='technical'?'Technical':'Interview'}</button>)}</div><button className="subtle-button" onClick={()=>isDone?notify('Already marked as read'):setState(setCompleted(state,lesson.id))}>{isDone?'✓ Read':'Mark as read'}</button></div></header>
   <div className="lesson-highlight"><span className="highlight-icon" aria-hidden="true">{tab==='simple'?'1':tab==='technical'?'2':'3'}</span><div><small>{tab==='simple'?'INTUITION':tab==='technical'?'TECHNICAL MEANING':'INTERVIEW EXPLANATION'}</small><p>{tab==='simple'?lesson.intuition:tab==='technical'?lesson.technical:lesson.interview}</p></div></div>
   <div className="lesson-body"><section className="lesson-section"><h2>3. Connect to what you already know</h2><p>{lesson.cs}</p></section><section className="lesson-section"><h2>4. Where it exists in this project</h2><p>{lesson.location}</p><details className="lesson-details source-details"><summary>Show the small code example and resource boundary</summary><pre className="code-snippet"><code>{lesson.snippet}</code><button aria-label="Copy code" onClick={()=>navigator.clipboard?.writeText(lesson.snippet)}>Copy</button></pre><div className="resource-line"><b>Resource</b><span>{lesson.resource}</span><b>Protection</b><span>{lesson.protection}</span></div></details></section>
    <details className="lesson-details"><summary>5–8. Why it exists, failure modes and trade-offs</summary>{whySections.map(([title,key])=><section className="lesson-section" key={key}><h2>{title}</h2><p>{String(lesson[key])}</p></section>)}</details><ConceptVisualization lesson={lesson}/>
    <section className="lesson-section apply-section"><h2>Apply it somewhere else</h2><p>Think of a different service you know. Where could this same idea protect a scarce resource or make behavior easier to reason about?</p><label htmlFor="apply-answer" className="eyebrow">YOUR EXAMPLE · SAVED LOCALLY FOR THIS CONCEPT</label><textarea id="apply-answer" value={application} onChange={e=>saveApplication(e.target.value)} placeholder="Write a short example in your own words…"/></section>
    <section className="quiz-panel"><div className="panel-head"><div><div className="eyebrow">ACTIVE RECALL</div><h2>Check your understanding</h2><p>Choose the response that best follows from the concept.</p></div>{state.quiz[lesson.id]&&<Badge>{state.quiz[lesson.id].correct}/{state.quiz[lesson.id].total} correct</Badge>}</div>{!quiz?<button className="button" onClick={()=>{setQuiz(true);setAnswered(null)}}>Start a scenario question →</button>:<><div className="quiz-count">QUESTION {qIndex+1} / {quizItems.length}</div><h3>{quizItems[qIndex].q}</h3><div className="quiz-options">{quizItems[qIndex].a.map((a,i)=><button key={a} disabled={answered!==null} className={answered===i?(i===quizItems[qIndex].correct?'correct':'incorrect'):''} onClick={()=>submitQuiz(i)}>{a}</button>)}</div>{answered!==null&&<div className="quiz-feedback" role="status"><b>{answered===quizItems[qIndex].correct?'Sound reasoning.':'Revisit the distinction.'}</b> {quizItems[qIndex].why}<button onClick={()=>{setQIndex((qIndex+1)%quizItems.length);setAnswered(null)}}>{qIndex===quizItems.length-1?'Try another round':'Next question'} →</button></div>}</>}</section>
    <details className="lesson-details"><summary>9–10. Interview answer and harder follow-up</summary>{interviewSections.map(([title,key])=><section className="lesson-section" key={key}><h2>{title}</h2><p>{String(lesson[key])}</p></section>)}</details>
    <div className="lesson-source-note"><Badge>[C] Code-derived</Badge><span>Source baseline: {project.appBaseline}. Historical measurements are labeled [M]; unsupported per-job values remain “Not measured.”</span></div>
    <div className="flashcard-row"><div><div className="eyebrow">RETRIEVAL PRACTICE</div><h3>What do you want to remember?</h3><p>{lesson.intuition}</p></div><div className="flashcard-actions"><button aria-pressed={state.flashcards[lesson.id]==='review'} onClick={()=>setState({...state,flashcards:{...state.flashcards,[lesson.id]:'review'}})}>Review again</button><button aria-pressed={state.flashcards[lesson.id]==='know'} onClick={()=>setState({...state,flashcards:{...state.flashcards,[lesson.id]:'know'}})}>Know it</button></div></div>
   </div></article></div>;
}

function ConceptVisualization({lesson}:{lesson:Lesson}){
  if(lesson.id==='singleflight-cache')return <div className="concept-viz"><div className="eyebrow">SEVEN SIMULTANEOUS CACHE MISSES · CONCEPTUAL</div><div className="flight-layout"><div className="caller-stack">{Array.from({length:7},(_,i)=><span key={i}>Caller {i+1} · same URL</span>)}</div><div className="flight-lines"><i/><i/><i/><i/><i/><i/><i/></div><div className="extractor-box"><b>1 extraction</b><small>leader work</small></div><div className="waiter-note">6 callers join the in-flight result</div></div><div className="contrast-row"><div><b>Cache only</b><span>7 misses can start 7 extractions before the first result is cached.</span></div><div><b>Cache + single-flight</b><span>One current extraction; later requests may hit the completed TTL cache.</span></div></div></div>;
  if(lesson.id==='streaming')return <div className="concept-viz"><div className="eyebrow">UPLOAD PATH · PYTHON HEAP VS DISK</div><div className="stream-compare"><div className="stream-card old"><small>OLD PATTERN · WHOLE-FILE BUFFER</small><b>49 MB file</b><span>→ `bytes` in Python memory → HTTP request</span><div className="memory-gauge"><i style={{width:'92%'}}/></div><em>large avoidable anonymous allocation</em></div><div className="stream-card new"><small>V1 · STREAM OPEN FILE</small><b>disk → small chunk → socket</b><span>read next chunk as HTTP client sends</span><div className="memory-gauge"><i style={{width:'16%'}}/></div><em>bounded application buffering; page cache still exists</em></div></div><p className="viz-caveat">The gauge is schematic, not a measured allocation or benchmark. Actual memory depends on HTTP buffers, kernel page cache and concurrency.</p></div>;
  if(lesson.id==='cpu-steal')return <div className="concept-viz"><div className="eyebrow">VIRTUALIZED CPU SCHEDULING</div><div className="hypervisor-stack"><div>Physical host CPU</div><i>↓ hypervisor schedules guests</i><div className="guest-row"><b>Other guest gets time</b><b className="ours">Our VM gets a turn</b></div><i>↓ guest scheduler</i><div>Bot threads and child processes</div></div><p className="viz-caveat">More bot workers compete inside the VM. They cannot reclaim time the hypervisor did not schedule to the VM.</p></div>;
  if(lesson.id==='durability-idempotency'||lesson.id==='distributed-systems')return <div className="concept-viz"><div className="eyebrow">LOCAL STATE VS REMOTE SIDE EFFECT</div><div className="state-compare"><div><small>CURRENT · SINGLE HOST</small><b>bot process</b><span>in-memory queue</span><span>SQLite history on local disk</span><span>best-effort interruption marker</span></div><div><small>FUTURE · MULTIPLE WORKERS</small><b>queue + worker fleet</b><span>durable job ownership</span><span>shared database/object storage</span><span>dedupe + lease/recovery rules</span></div></div><p className="viz-caveat">The second diagram is a design exercise, not implemented v1 architecture.</p></div>;
  if(lesson.id==='sqlite-wal')return <div className="concept-viz"><div className="eyebrow">WRITE-AHEAD LOG · SIMPLIFIED</div><div className="wal-flow"><span>Reader A sees stable snapshot</span><b>Database file</b><b className="wal">WAL append ← Writer</b><span>Checkpoint later merges pages</span></div><p className="viz-caveat">WAL supports local readers while writes append; SQLite still serializes writers. It does not make download jobs durable.</p></div>;
  return null;
}

function InterviewPage({state,setState}:{state:LearningState;setState:(s:LearningState)=>void}){
  const [mode,setMode]=useState<'bank'|'mock'|'cards'>('bank');const [level,setLevel]=useState('All');const [topic,setTopic]=useState('All');const [idx,setIdx]=useState(0);const [show,setShow]=useState(false);const [search,setSearch]=useState('');
  const topics=['All',...Array.from(new Set(questions.map(q=>q.topic)))];
  const list=questions.filter(q=>(level==='All'||q.level===level)&&(topic==='All'||q.topic===topic)&&q.question.toLowerCase().includes(search.toLowerCase()));
  const current=list[idx%Math.max(1,list.length)];
  const weakest=useMemo(()=>{const vals=Object.entries(state.confidence);return vals.sort((a,b)=>a[1]-b[1])[0]?.[0]},[state.confidence]);
  const mockList=useMemo(()=>{const low=weakest?questions.filter(q=>q.topic===weakest):[];return low.length?low:questions},[weakest]);
  return <><SectionTitle eyebrow="100 QUESTIONS · FIVE LEVELS" title="Interview gym" description="Practice a topic from fundamentals through production diagnosis and system evolution. Self-grade honestly; weak topics are prioritised locally."/><div className="tabbar interview-tabs">{[['bank','Question bank'],['mock','Mock interview'],['cards','Flashcards']].map(([id,t])=><button key={id} className={mode===id?'selected':''} onClick={()=>{setMode(id as typeof mode);setIdx(0);setShow(false)}}>{t}</button>)}</div>
    {mode==='bank'&&<><div className="filterbar"><input className="search-input" value={search} onChange={e=>{setSearch(e.target.value);setIdx(0)}} placeholder="Search questions…"/><select value={level} onChange={e=>{setLevel(e.target.value);setIdx(0)}}><option>All</option>{['A','B','C','D','E'].map(l=><option key={l} value={l}>Level {l}</option>)}</select><select value={topic} onChange={e=>{setTopic(e.target.value);setIdx(0)}}>{topics.map(t=><option key={t}>{t}</option>)}</select><Badge>{questions.length} total · {list.length} shown</Badge></div>{current&&<QuestionCard key={current.id} q={current} show={show} setShow={setShow}/>}<div className="question-nav"><button onClick={()=>setIdx(Math.max(0,idx-1))}>← Previous</button><span>{idx+1} / {list.length}</span><button onClick={()=>{setIdx((idx+1)%Math.max(1,list.length));setShow(false)}}>Next question →</button></div></>}
    {mode==='mock'&&current&&<div className="mock-card"><div className="mock-top"><Badge>MOCK INTERVIEW</Badge><span>{weakest?`Weak topic focus: ${weakest}`:'One question at a time'}</span></div><div className="eyebrow">LEVEL {mockList[idx%mockList.length].level} · {mockList[idx%mockList.length].topic}</div><h2>{mockList[idx%mockList.length].question}</h2><button className="subtle-button" onClick={()=>setShow(!show)}>{show?'Hide answer':'Reveal answer'}</button>{show&&<QuestionCard q={mockList[idx%mockList.length]} show setShow={setShow} compact/>}<div className="confidence"><span>How confident were you?</span>{[['Don’t know',1],['Weak',2],['Okay',3],['Strong',4]].map(([label,n])=><button key={String(n)} onClick={()=>{const q=mockList[idx%mockList.length];setState({...state,confidence:{...state.confidence,[q.topic]:Number(n)}});setIdx((idx+1)%mockList.length);setShow(false)}}>{label}</button>)}</div></div>}
    {mode==='cards'&&<div className="cards-page"><div className="panel-head"><div><div className="eyebrow">LOCAL FLASHCARDS</div><h2>Retrieve, then review</h2></div><Badge>{Object.keys(state.flashcards).length} tracked</Badge></div><div className="flashcard-grid">{concepts.map(c=><div className="flashcard" key={c.id}><div className="eyebrow">{c.group}</div><h3>{c.title}</h3><p>{c.intuition}</p><div><button className={state.flashcards[c.id]==='know'?'picked':''} onClick={()=>setState({...state,flashcards:{...state.flashcards,[c.id]:'know'}})}>✓ Know</button><button className={state.flashcards[c.id]==='review'?'picked':''} onClick={()=>setState({...state,flashcards:{...state.flashcards,[c.id]:'review'}})}>↻ Review</button></div></div>)}</div></div>}
  </>;
}
function QuestionCard({q,show,setShow,compact=false}:{q:(typeof questions)[number];show:boolean;setShow:(s:boolean)=>void;compact?:boolean}){
 return <article className={'question-card '+(compact?'compact':'')}><div className="question-meta"><Badge>LEVEL {q.level}</Badge><span>{q.topic}</span></div><h2>{q.question}</h2><details className="lesson-details hint-disclosure"><summary>Need a hint?</summary><div className="hint-box"><b>Hint</b><p>{q.hint}</p></div></details>{show?<div className="answer-grid"><div><div className="eyebrow">CONCISE ANSWER</div><p>{q.concise}</p><details className="lesson-details"><summary>Open the full answer and rubric</summary><div className="lesson-section"><h3>Deep answer</h3><p>{q.deep}</p></div><div className="lesson-section"><h3>Project example</h3><p>{q.project}</p></div><div className="lesson-section"><h3>Weak answer</h3><p>{q.weak}</p></div><div className="lesson-section"><h3>Strong answer</h3><p>{q.strong}</p></div><div className="lesson-section"><h3>Likely follow-up</h3><p>{q.followup}</p></div></details></div></div>:<button className="button" onClick={()=>setShow(true)}>Reveal concise answer</button>}</article>;
}

function IncidentPage(){
 const [active,setActive]=useState(incidents[0].id);const [choice,setChoice]=useState<number|null>(null);const [revealed,setRevealed]=useState(false);const item=incidents.find(x=>x.id===active)!;
 function selectIncident(id:string){setActive(id);setChoice(null);setRevealed(false)}
 return <><SectionTitle eyebrow="INVESTIGATION PRACTICE" title="Incident lab" description="Start with the symptom. Inspect evidence, choose a hypothesis, then reveal the diagnosis and production lesson."/><div className="incident-layout"><aside className="incident-list" aria-label="Choose an incident">{incidents.map(i=><button key={i.id} className={active===i.id?'active':''} aria-current={active===i.id?'true':undefined} onClick={()=>selectIncident(i.id)}><span aria-hidden="true">Case</span><b>{i.title}</b><small>{i.evidenceTag}</small></button>)}</aside><article className="incident-detail"><div className="incident-banner"><div className="eyebrow">CASE FILE · {item.evidenceTag}</div><h2>{item.title}</h2><p>{item.symptom}</p></div>
  <div className="incident-columns"><details className="lesson-details"><summary>1. Reveal the available measurements</summary>{item.evidence.map(x=><p className="evidence-point" key={x}><span aria-hidden="true">↳</span>{x}</p>)}</details><details className="lesson-details"><summary>2. Open a code or system hint</summary>{item.hints.map(x=><p className="evidence-point" key={x}><span aria-hidden="true">↳</span>{x}</p>)}</details></div>
  <div className="investigate"><div className="eyebrow">3. WHAT WOULD YOU INVESTIGATE FIRST?</div>{item.options.map((o,i)=><button key={o} className={choice===i?'chosen':''} aria-pressed={choice===i} onClick={()=>{setChoice(i);setRevealed(false)}}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}{choice!==null&&<button className="button" onClick={()=>setRevealed(true)}>Commit to this hypothesis →</button>}</div>
  {revealed&&<div className="diagnosis" aria-live="polite"><div className="eyebrow">4. WHAT THE EVIDENCE SUPPORTS</div><h3>Diagnosis</h3><p>{item.diagnosis}</p><div className="diagnosis-grid">{[['Fix',item.fix],['Regression test',item.test],['Production verification',item.verify],['Lesson learned',item.lesson]].map(([k,v])=><div key={k}><small>{k}</small><p>{v}</p></div>)}</div><Badge>{item.evidenceTag}</Badge></div>}
 </article></div></>;
}

function Simulators(){const [which,setWhich]=useState('Concurrency timeline');return <><SectionTitle eyebrow="WHAT-IF LAB · SIMULATED, NOT A BENCHMARK" title="Make the system move" description="Change an input and see the relationship. The numbers below are educational estimates unless labeled [M]."/><div className="sim-nav">{['Concurrency timeline','Download queue','UploadGate','Memory & swap','Percentiles','Little’s Law','Capacity planning','Bottleneck quiz','Scale ladder'].map(x=><button className={which===x?'on':''} onClick={()=>setWhich(x)} key={x}>{x}</button>)}</div>{which==='Concurrency timeline'&&<ConcurrencySim/>}{which==='Download queue'&&<QueueSim/>}{which==='UploadGate'&&<UploadSim/>}{which==='Memory & swap'&&<MemorySim/>}{which==='Percentiles'&&<PercentileSim/>}{which==='Little’s Law'&&<LittleLawSim/>}{which==='Capacity planning'&&<CapacitySim/>}{which==='Bottleneck quiz'&&<BottleneckSim/>}{which==='Scale ladder'&&<ScaleSim/>}</>}

function ConcurrencySim(){const [mode,setMode]=useState('Async I/O');const [run,setRun]=useState(false);return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">EVENT LOOP · OS THREADS · PROCESSES</div><h2>Concurrency timeline</h2><p className="muted">Same network-wait workload; see how the coordinator uses waiting time.</p></div><select value={mode} onChange={e=>{setMode(e.target.value);setRun(false)}}><option>Async I/O</option><option>Blocking synchronous</option><option>ThreadPoolExecutor</option><option>ProcessPoolExecutor</option></select></div><button className="button green-button" onClick={()=>setRun(!run)}>{run?'Reset timeline':'Run timeline →'}</button><div className="timeline">{['Request A','Request B','Request C'].map((x,i)=><div className="timeline-row" key={x}><b>{x}</b><div className="timeline-lane"><span className={run?`work ${mode==='Blocking synchronous'&&i>0?'delayed':''}`:''}>{run?(mode==='Blocking synchronous'&&i>0?'WAITING TURN':'WORK → WAIT → RESULT'):'READY'}</span>{mode==='Async I/O'&&run&&<small>event loop handles another task at await</small>}</div></div>)}</div><div className="callout"><b>Key distinction</b><span>Async can overlap waits; it does not execute CPU-heavy Python on multiple cores. Threads are OS scheduled and share memory; process-pool tasks need serialization and separate memory. These lanes are a simplified [E] teaching model, not a runtime trace.</span></div></div>}

function QueueSim(){const [prediction,setPrediction]=useState<string[]>([]);const [revealed,setRevealed]=useState(false);const pending=['A3','B1','Premium1'];const answer=['Premium1','B1','A3'];const add=(j:string)=>!prediction.includes(j)&&prediction.length<pending.length&&setPrediction([...prediction,j]);return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">THREE GLOBAL SLOTS · TWO PER USER</div><h2>Predict the next job</h2><p className="muted">A1 and A2 are running. A3 is at the per-user cap; B1 and Premium1 are waiting.</p></div><Badge>[C] policy-inspired simplification</Badge></div><div className="slot-row">{['A1 · RUNNING','A2 · RUNNING','OPEN SLOT'].map(x=><div className={x==='OPEN SLOT'?'slot-empty':'slot-live'} key={x}>{x}</div>)}</div><div className="prediction-options">{pending.map(j=><button key={j} className={prediction.includes(j)?'chosen':''} disabled={revealed} onClick={()=>add(j)}>{j}{j==='A3'?' · user A at limit':j==='Premium1'?' · priority':''}</button>)}</div><div className="prediction-row"><span>Your predicted order: {prediction.length?prediction.join(' → '):'choose a job order above'}</span><button className="button green-button" disabled={prediction.length!==3} onClick={()=>setRevealed(true)}>Reveal scheduler order</button></div>{revealed&&<div className="queue-reveal"><div className="queue-steps">{answer.map((j,i)=><div key={j}><i>{i+1}</i><b>{j}</b><small>{j==='A3'?'User A now has a free permit':j==='Premium1'?'Priority rank moves it ahead':'Eligible user gets the next slot'}</small></div>)}</div><p>The real queue uses priority rank then ticket order, and chooses the first owner under their cap. This scenario simplifies arrival timing to highlight eligibility and priority. Check bot/services/dl_queue.py for exact behavior.</p></div>}</div>}

function UploadSim(){const [slots,setSlots]=useState(2);const [budget,setBudget]=useState(100);const [files,setFiles]=useState([49,40,20]);const admitted=(()=>{let used=0,n=0;for(const size of files){const cost=Math.min(size,budget);if(n<slots&&used+cost<=budget){n++;used+=cost}}return {n,used}})();return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">SLOT + BYTE RESERVATION</div><h2>UploadGate</h2><p className="muted">Edit file sizes and limits. This is a simplified fit check; the real gate is strict FIFO.</p></div><Badge>[C] defaults: 2 slots · 100 MiB</Badge></div><div className="slider-grid"><Slider label="Concurrent slots" value={slots} min={1} max={4} onChange={setSlots} unit=""/><Slider label="Byte budget" value={budget} min={30} max={150} onChange={setBudget} unit=" MiB"/></div><div className="file-bars">{files.map((f,i)=><label key={i}>File {i+1}<input type="range" min="5" max="100" value={f} onChange={e=>setFiles(files.map((x,j)=>j===i?Number(e.target.value):x))}/><b>{f} MiB</b></label>)}</div><div className="gate-result"><b>{admitted.n} / {files.length} files admitted now</b><span>{admitted.used} / {budget} MiB reserved</span><div className="progress-track"><i style={{width:`${Math.min(100,admitted.used/budget*100)}%`}}/></div></div><p className="muted">The actual gate prevents later small files overtaking the head waiter. A file larger than the whole budget consumes the full budget and can run alone.</p></div>}

function Slider({label,value,min,max,onChange,unit}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void;unit:string}){return <label className="slider-control"><span>{label}<b>{value}{unit}</b></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}

function MemorySim(){const [anon,setAnon]=useState(430);const [cache,setCache]=useState(180);const [other,setOther]=useState(250);const [swap,setSwap]=useState(0);const total=952,approx=Math.max(0,total-anon-cache*.25-other);const pressure=approx<100?'High conceptual pressure':approx<220?'Watch reclaim and activity':'Headroom in this simplified model';return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">VM MEMORY MODEL</div><h2>Where did the memory go?</h2><p className="muted">Host snapshot: about 952 MiB RAM and 2 GiB swap. Adjust conceptual categories below.</p></div><Badge>[E] simplified, not Linux MemAvailable</Badge></div><div className="memory-stacked"><i style={{width:`${anon/total*100}%`}} className="anon"/><i style={{width:`${cache/total*100}%`}} className="cache"/><i style={{width:`${other/total*100}%`}} className="other"/><i style={{width:`${approx/total*100}%`}} className="free"/></div><div className="memory-legend"><span><i className="anon"/>Anonymous {anon} MiB</span><span><i className="cache"/>Page cache {cache} MiB</span><span><i className="other"/>Other {other} MiB</span><span><i className="free"/>Rough residual {approx} MiB</span></div><div className="slider-grid"><Slider label="Anonymous / resident app memory" value={anon} min={100} max={700} onChange={setAnon} unit=" MiB"/><Slider label="Page cache (partly reclaimable)" value={cache} min={0} max={400} onChange={setCache} unit=" MiB"/><Slider label="Other host/cgroup memory" value={other} min={100} max={600} onChange={setOther} unit=" MiB"/><Slider label="Swap occupied" value={swap} min={0} max={2048} onChange={setSwap} unit=" MiB"/></div><div className={`pressure-callout ${approx<100?'warn':''}`}><b>{pressure}</b><span>{swap>0?'Swap occupancy alone is not proof of active thrashing. Check swap-in/out rate, memory PSI and latency.':'Combine available memory with active swap and PSI; no single number is the whole story.'}</span></div><div className="callout"><b>Academic connection</b><span>A page fault is the virtual-memory mechanism from OS. A major fault needs storage I/O; page cache may be reclaimed, while anonymous pages may be swapped. The model simplifies Linux accounting, reclaim and shared pages.</span></div></div>}

function PercentileSim(){const [tail,setTail]=useState(3);const vals=[1.2,1.4,1.5,1.5,1.7,1.8,1.9,2.1,2.3,2.5,2.7,2.8,3.1,3.4,3.7,4.1,4.8,5.2,6.1,8,12,18,24,34,...Array(tail).fill(45)];return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">LATENCY DISTRIBUTION</div><h2>Mean vs tail</h2><p className="muted">Add slow observations to see how the mean and percentiles respond.</p></div><Badge>[E] illustrative samples</Badge></div><Slider label="Additional slow observations" value={tail} min={0} max={20} onChange={setTail} unit=""/><div className="percentile-cards">{[['Mean',vals.reduce((a,b)=>a+b,0)/vals.length],['p50',percentile(vals,.5)],['p90',percentile(vals,.9)],['p95',percentile(vals,.95)],['p99',percentile(vals,.99)]].map(([n,v])=><div key={String(n)}><small>{n}</small><b>{Number(v).toFixed(1)}s</b></div>)}</div><div className="bar-chart">{vals.map((v,i)=><i key={i} title={`${v}s`} style={{height:`${Math.max(5,Number(v)/45*100)}%`}} className={v>=34?'tail-bar':''}/>)}</div><p className="muted">The source project reports warm-up timing percentiles separately from user-job samples. A small sample makes p99 unstable; these generated values are not project measurements.</p></div>}

function LittleLawSim(){const [rate,setRate]=useState(3);const [time,setTime]=useState(10);const [workers,setWorkers]=useState(3);return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">QUEUEING THEORY · L = λW</div><h2>Little’s Law, in motion</h2><p className="muted">Use jobs/minute and minutes in system. Stable long-run average only.</p></div><Badge>[E] teaching example</Badge></div><div className="slider-grid"><Slider label="Arrivals λ" value={rate} min={1} max={20} onChange={setRate} unit=" jobs/min"/><Slider label="Time in system W" value={time} min={1} max={30} onChange={setTime} unit=" min"/><Slider label="Worker slots (context only)" value={workers} min={1} max={10} onChange={setWorkers} unit=""/></div><div className="law-equation"><span>L</span><i>=</i><b>{rate}</b><i>×</i><b>{time}</b><i>=</i><strong>{littleLaw(rate,time)}<small>average jobs in system</small></strong></div><div className="queue-visual">{Array.from({length:Math.min(30,Math.round(littleLaw(rate,time)))},(_,i)=><i key={i} className={i<workers?'worker-job':''}/>)}</div><div className="callout"><b>Why daily average misleads</b><span>1,000 jobs/day spread evenly is about 0.69 jobs/minute. 100 jobs arriving in 10 minutes is 10 jobs/minute—a different burst. [E] These are examples, not this bot’s measured traffic.</span></div></div>}

function CapacitySim(){const [day,setDay]=useState(100);const [burst,setBurst]=useState(12);const [size,setSize]=useState(25);const [dl,setDl]=useState(120);const [up,setUp]=useState(90);const [slots,setSlots]=useState(3);const avgMbps=mbps(size*day,86400);const burstMbps=mbps(size*burst,600);const gb=gigabytesPerDay(day,size);const active=burst*(dl+up)/600;return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">CAPACITY ESTIMATOR</div><h2>Estimate each resource</h2><p className="muted">Set an assumed workload. Outputs are [E], not a production forecast.</p></div><Badge>Not measured: actual jobs/day and file sizes</Badge></div><div className="slider-grid"><Slider label="Jobs per day" value={day} min={1} max={5000} onChange={setDay} unit=""/><Slider label="Burst jobs in 10 minutes" value={burst} min={1} max={500} onChange={setBurst} unit=""/><Slider label="Average media size" value={size} min={1} max={49} onChange={setSize} unit=" MB"/><Slider label="Download time per job" value={dl} min={10} max={900} onChange={setDl} unit=" s"/><Slider label="Upload time per job" value={up} min={10} max={900} onChange={setUp} unit=" s"/><Slider label="Download worker slots" value={slots} min={1} max={20} onChange={setSlots} unit=""/></div><div className="estimate-grid"><div><small>AVERAGE INGRESS</small><b>{avgMbps.toFixed(2)} Mbps</b><span>jobs/day × MB × 8 / day</span></div><div><small>AVERAGE EGRESS</small><b>{avgMbps.toFixed(2)} Mbps</b><span>assumes same media size uploaded</span></div><div><small>TOTAL MEDIA / DAY</small><b>{gb.toFixed(1)} GB</b><span>before retries/protocol overhead</span></div><div><small>BURST INGRESS</small><b>{burstMbps.toFixed(1)} Mbps</b><span>burst jobs × MB × 8 / 600s</span></div><div><small>ARRIVAL WORK (L≈λW)</small><b>{active.toFixed(1)} jobs</b><span>burst rate × download+upload time</span></div><div><small>TEMP FILES</small><b>Up to ~{Math.min(burst,Math.ceil(burst*dl/600),slots*10)*size} MB (rough)</b><span>real overlap depends on stage lifecycle</span></div></div><p className="muted">This assumes uniform sizes and durations. Real capacity planning uses distributions, separates download/upload legs, includes retry overhead and measures temporary-file overlap.</p></div>}

function BottleneckSim(){const [answer,setAnswer]=useState<string|null>(null);const [scenario,setScenario]=useState(0);const cases=[{s:'CPU busy is low, steal is high, and all jobs slow at once.',a:'CPU steal / virtualization wait',why:'Guest processes may be runnable but the hypervisor schedules other guests. Adding processes cannot reclaim stolen time.'},{s:'Downloads finish but queue of completed files grows; upload slots stay full.',a:'Telegram upload capacity',why:'The downstream send stage is constrained; additional download concurrency could grow disk backlog.'},{s:'Available memory falls, swap-in spikes, memory PSI rises during concurrent sends.',a:'Memory pressure during upload overlap',why:'Correlate active paging and PSI; inspect streaming path, upload concurrency and cgroup limits.'},{s:'Only one URL is slow for all callers; metadata pool is full of identical extraction.',a:'Duplicate metadata work / missing coalescing',why:'Single-flight should make concurrent identical requests share one extraction.'}];const c=cases[scenario];return <div className="panel sim-panel"><div className="eyebrow">DIAGNOSIS PRACTICE · {scenario+1}/{cases.length}</div><h2>Which resource is probably limiting?</h2><div className="symptom-card">“{c.s}”</div><div className="bottleneck-options">{['CPU saturation','CPU steal','RAM / memory pressure','Disk throughput','Network / external API','Queue policy','Telegram upload','Duplicate work'].map(x=><button className={answer===x?'chosen':''} onClick={()=>setAnswer(x)} key={x}>{x}</button>)}</div>{answer&&<div className="quiz-feedback"><b>{answer===c.a?'Good diagnosis.':`Consider: ${c.a}.`}</b> {c.why}<button onClick={()=>{setScenario((scenario+1)%cases.length);setAnswer(null)}}>Next symptom →</button></div>}</div>}

function ScaleSim(){const [level,setLevel]=useState(1);const [choice,setChoice]=useState('');const s=scaling[level];const options=['Increase VM size','Increase concurrency','PostgreSQL','Redis / durable queue','More worker processes','Object storage','Multiple nodes','Kubernetes'];return <div className="panel sim-panel"><div className="panel-head"><div><div className="eyebrow">CHOOSE FIRST · THEN REVEAL</div><h2>What changes at scale?</h2><p className="muted">A multiplier is a thought experiment, not evidence of a bottleneck.</p></div><Badge>{s.title}</Badge></div><div className="scale-slider">{scaling.map((x,i)=><button className={level===i?'on':''} key={x.multiplier} onClick={()=>{setLevel(i);setChoice('')}}>{x.multiplier.toLocaleString()}×</button>)}</div><div className="symptom-card">What do you think breaks first? Choose one option.</div><div className="bottleneck-options">{options.map(x=><button className={choice===x?'chosen':''} onClick={()=>setChoice(x)} key={x}>{x}</button>)}</div>{choice&&<div className="scale-reveal"><div className="eyebrow">REVEAL · {s.title.toUpperCase()}</div><p><b>What might break:</b> {s.breaks}</p><p><b>Measure:</b> {s.metric}</p><p><b>Reasonable next change:</b> {s.change}</p><p className="muted">Your choice: {choice}. It becomes justified only if evidence points to its specific problem.</p></div>}</div>}

function RebuildBoss(){
 const [mode,setMode]=useState<'rebuild'|'100k'>('rebuild');
 const [choices,setChoices]=useState<Record<string,string>>({});
 const [step,setStep]=useState(0);const [reveal,setReveal]=useState(false);
 const decisions:[string,string[]][]=[
  ['Ingress',['Long polling','Webhook']],['Handler model',['Synchronous','Asyncio']],['Blocking work',['Same event loop','Threads','Processes']],
  ['Scheduling',['Start immediately','Fair in-memory queue','Durable distributed queue']],['Admission',['No limits','Concurrency + rate limits']],
  ['Metadata',['Extract every request','Cache only','Cache + single-flight']],['Upload',['Buffer full file','Stream from disk']],
  ['State',['JSON only','SQLite for history + local JSON']],['Cancellation',['Ignore cancellation','Cooperative checks']],
  ['Retries',['Retry every error','Classify transient/permanent + bounded retries']],['Health',['Process active only','Heartbeat + dependency/disk checks']],
  ['Deployment',['Interactive shell','systemd/cgroups']],['Scale',['Add Kafka first','Measure bottleneck, then evolve']]
 ];
 const real:Record<string,string>={Ingress:'Long polling','Handler model':'Asyncio','Blocking work':'Threads',Scheduling:'Fair in-memory queue',Admission:'Concurrency + rate limits',Metadata:'Cache + single-flight',Upload:'Stream from disk',State:'SQLite for history + local JSON',Cancellation:'Cooperative checks',Retries:'Classify transient/permanent + bounded retries',Health:'Heartbeat + dependency/disk checks',Deployment:'systemd/cgroups',Scale:'Measure bottleneck, then evolve'};
 const current=decisions[step];const complete=Object.keys(choices).length===decisions.length;
 function changeMode(next:'rebuild'|'100k'){setMode(next);setReveal(false);setStep(0)}
 return <><SectionTitle eyebrow="DESIGN INTERVIEW WORKBENCH" title="Rebuild the downloader" description="Make one boundary decision at a time. Explain your reasoning before comparing it with the shipped design."/>
  <div className="tabbar"><button className={mode==='rebuild'?'selected':''} aria-pressed={mode==='rebuild'} onClick={()=>changeMode('rebuild')}>Rebuild current project</button><button className={mode==='100k'?'selected':''} aria-pressed={mode==='100k'} onClick={()=>changeMode('100k')}>System design · 100k jobs/day</button></div>
  {mode==='100k'?<SystemDesignMode/>:<div>
   <div className="boss-requirements"><div className="eyebrow">REQUIREMENTS ONLY</div><h2>Design a service that:</h2><ul><li>Accepts media links from Telegram users and returns the selected media.</li><li>Runs on a small single VM initially, with unknown burst size and media distribution.</li><li>Has a final upload-size cap and should remain responsive during network waits.</li><li>Bounds resource use and explains behavior if the process restarts during a job.</li></ul><p>No job/day or peak concurrency is provided. State assumptions; do not invent capacity figures.</p></div>
   <div className="panel boss-panel"><div className="panel-head"><div><div className="eyebrow">YOUR DESIGN · DECISION {step+1} OF {decisions.length}</div><h2>Choose the {current[0].toLowerCase()} approach</h2></div><span>{Object.keys(choices).length} of {decisions.length} decisions recorded</span></div>
    <div className="progress-track" role="progressbar" aria-label="Design decisions completed" aria-valuemin={0} aria-valuemax={decisions.length} aria-valuenow={Object.keys(choices).length}><i style={{width:Object.keys(choices).length/decisions.length*100+'%'}}/></div>
    <div className="decision-row" key={current[0]}><b>{current[0]}</b><div>{current[1].map(option=><button type="button" aria-pressed={choices[current[0]]===option} key={option} className={choices[current[0]]===option?'chosen':''} onClick={()=>setChoices({...choices,[current[0]]:option})}>{option}</button>)}</div></div>
    <div className="design-navigation"><button className="subtle-button" disabled={step===0} onClick={()=>setStep(step-1)}>Previous decision</button><span>{Object.keys(choices).length} selected · you can revise earlier choices</span>{step<decisions.length-1?<button className="button" disabled={!choices[current[0]]} onClick={()=>setStep(step+1)}>Next decision →</button>:<button className="button" disabled={!complete} onClick={()=>setReveal(true)}>Compare with v1 →</button>}</div>
    {reveal&&<div className="boss-reveal"><h3>One reasonable shipped design</h3><p>v1 uses long polling, PTB/asyncio, blocking work in bounded thread pools, a fair in-memory queue, local rate limits, metadata cache + single-flight, file-backed streaming + UploadGate, SQLite WAL history, cooperative cancellation, bounded classified retries, heartbeat/health checks, and systemd/cgroups.</p>{decisions.map(([name])=><div key={name} className={choices[name]===real[name]?'compare-match':'compare-diff'}><b>{name}</b><span>Your choice: {choices[name]}</span><span>v1: {real[name]}</span><small>{choices[name]===real[name]?'Same as v1; alternatives may still be valid.':'Different from v1; discuss requirements and trade-offs behind your choice.'}</small></div>)}<div className="callout"><b>One reasonable design, not the only right one</b><span>Webhook ingress, durable work state or multiple workers can fit different requirements. First measure the workload and define recovery semantics.</span></div></div>}
   </div>
  </div>}
 </>;
}

function SystemDesignMode(){
 const prompts:[string,string][]=[['Requirements','Define job completion, supported media, latency, failure recovery, delivery semantics and availability goals.'],['Estimation','Estimate average and burst arrivals, bytes per job, bandwidth, worker concurrency and temporary disk. State assumptions.'],['API','Choose Telegram polling or webhook and describe update acknowledgement, deduplication and user status.'],['Data','Separate job state, history, cache, temporary media and secrets. Which state must survive restart?'],['Queueing','Choose admission, fairness, priority, bounded backlog and worker ownership.'],['Processing','Place metadata, download, Deno/FFmpeg, temporary storage and upload into measurable stages.'],['Failure','Explain retries, cancellation, timeouts, ambiguous upload outcome and idempotency.'],['Scaling','Describe evolution from one node; name the measured trigger for every added component.']];
 const [notes,setNotes]=useState<Record<string,string>>({});const [shown,setShown]=useState(false);const [step,setStep]=useState(0);
 const complete=prompts.filter(([k])=>notes[k]?.trim()).length;const current=prompts[step];
 return <><div className="boss-requirements"><div className="eyebrow">INTERVIEW PROMPT · REQUIREMENTS ONLY</div><h2>Design a Telegram media downloader for 100,000 jobs/day.</h2><ul><li>Users submit URLs and receive media in the same chat.</li><li>External media sites and Telegram have variable response time and quotas.</li><li>Burst rate, file sizes, latency target, availability and retry semantics are unspecified.</li><li>Explain fairness, temporary storage, restart recovery and duplicate/lost work.</li></ul><p>Ask clarifying questions or state assumptions. Jobs per day alone are not enough for exact sizing.</p></div>
  <div className="design-workbench"><div className="eyebrow">YOUR DESIGN NOTES · {complete}/{prompts.length} SECTIONS STARTED</div><div className="progress-track" role="progressbar" aria-label="Design sections started" aria-valuemin={0} aria-valuemax={prompts.length} aria-valuenow={complete}><i style={{width:complete/prompts.length*100+'%'}}/></div>
   <div className="design-prompt" key={current[0]}><span>STEP {step+1} OF {prompts.length} · {current[0]}</span><b>{current[1]}</b><label htmlFor="design-note">Your notes for {current[0].toLowerCase()}</label><textarea id="design-note" value={notes[current[0]]||''} onChange={e=>setNotes({...notes,[current[0]]:e.target.value})} placeholder="Write your reasoning…"/></div>
   <div className="design-navigation"><button className="subtle-button" disabled={step===0} onClick={()=>setStep(step-1)}>Previous topic</button><span>{complete} of {prompts.length} topics started</span>{step<prompts.length-1?<button className="button" disabled={!notes[current[0]]?.trim()} onClick={()=>setStep(step+1)}>Next topic →</button>:<button className="button" disabled={complete<prompts.length} onClick={()=>setShown(true)}>Compare with one design →</button>}</div>
  </div>
  {shown&&<div className="panel boss-reveal"><div className="eyebrow">ONE REASONABLE DESIGN · ASSUMPTIONS EXPLICIT</div><h2>Scale the boundaries that need it</h2><p>Assume restart recovery and multi-worker throughput are required; the prompt does not give burst rate, mean file size or an SLO, so exact workers, bandwidth and storage are not calculated. Start with ingress, persist an idempotent job record, then use a durable queue and leased worker ownership. Stage large files in object storage or bounded shared storage, isolate media tools, and separately limit Telegram uploads. Persist outcomes and reconcile ambiguous delivery when provider capabilities allow.</p><div className="diagnosis-grid"><div><small>Estimation next</small><p>100,000 / 86,400 ≈ 1.16 jobs/s average [E]. Ask for burst jobs/min, MB/job, durations and retry rate; use L=λW as a stable-average check, then model bursts and each stage.</p></div><div><small>Data choice</small><p>Relational job state can support shared ownership and transactions; object storage holds large files; cache stores reusable derived data.</p></div><div><small>Reliability</small><p>At-least-once delivery requires idempotent transitions, retry limits and recovery handling. Exactly-once external delivery is not assumed.</p></div></div></div>}
 </>;
}

function Portfolio(){const [audience,setAudience]=useState('SDE interviewer');const [duration,setDuration]=useState('2 minutes');const scripts:Record<string,Record<string,string>>={
 'Recruiter':{'30 seconds':'I built and operate a Telegram media-downloader bot. I focused on keeping a small production VM responsive and safe by bounding concurrency, streaming uploads and measuring behavior before adding infrastructure.','2 minutes':'This is a self-hosted Telegram bot using PTB/asyncio to guide media requests, yt-dlp for downloads, and FFmpeg where needed. I added a fair download queue and per-user limits, metadata single-flight, UploadGate and streamed file uploads. History is in local SQLite WAL; production uses systemd/cgroups with Kuma health monitoring. The production-stable app is v1.0.0. I am careful not to claim scale the measurements did not show.','5 minutes':'Start with a single-node backend that accepts Telegram links, extracts metadata, queues downloads, writes to temporary disk, streams media to Telegram, and records history. The most interesting engineering work was aligning concurrency with a constrained VM: blocking extraction moved off the event loop, identical metadata requests coalesce, downloads are admitted fairly, and uploads have separate slot/byte limits and stream from disk. SQLite stores durable history, but job execution is not resumable. Tests cover the actual failure paths. A 24-hour comparison showed lower average swap activity and better warm-up tails, but CPU steal changed and user job sample was small, so I describe it as correlated evidence, not causal proof. The lesson was to measure first and keep architecture simple until a requirement appears.','15 minutes':'Walk through request lifecycle, event-loop boundaries, metadata cache vs in-flight coalescing, fair queue and per-user caps, thread pools vs process pools, disk staging and streamed upload, UploadGate, SQLite WAL vs volatile job state, timeout/cancellation ambiguity, cgroup/systemd limits, health checks, experiments/confounders, and what would trigger a durable distributed queue. Emphasize code/test evidence, historical measurement limits and no unsupported scale claim.'},
 'SDE interviewer':{'30 seconds':'A single-node async Telegram backend uses bounded threads for blocking yt-dlp, a fair queue for download admission, and a byte-aware gate plus streaming for uploads. I optimized based on resource constraints and kept durable history separate from volatile job execution.','2 minutes':'The bot receives Telegram updates via PTB. Async handlers validate inputs and rate-limit users, metadata is cached and coalesced, then jobs enter an in-memory fair queue with global/per-user limits. Blocking yt-dlp runs in a thread pool and can invoke FFmpeg/Deno subprocesses. Files stage on temporary disk. UploadGate reserves slot and byte budget, and PTB streams the open file handle. SQLite WAL stores history, but the queue/jobs are not resumable after restart. I chose threads because extraction/download are largely I/O or subprocess work and no GIL-bound Python bottleneck was measured.','5 minutes':'[C] Outline each boundary and capacity guard; discuss cache vs single-flight and fairness. [C] Explain BadRequest inheritance-order regression corrected in commit 830f351 and focused passing tests. [M] The 24-hour report’s host-level swap-in/out and PSI fell, but CPU steal also changed and user-job sample size was too small for a user-latency claim. [R] I would instrument queue wait, phase duration and per-job resources before changing concurrency.','15 minutes':'Use requirements and workload first, draw the request path, make queue and persistence semantics explicit, estimate bytes/time, identify failure and retry semantics, then propose staged scaling triggers. Defend why no Redis/Celery/process pool and what evidence would change that choice.'},
 'DevOps / SRE':{'30 seconds':'The bot is one systemd-managed process with cgroup resource caps, local heartbeat/health checks and Kuma. I treat process liveness, dependency health and successful user jobs as different signals.','2 minutes':'Production is a small Oracle VM with shared CPU, constrained RAM and swap. systemd supervises the bot and cgroups bound memory/CPU/tasks; Kuma and bgutil are container side services; WARP is optional host egress. A health daemon combines unit status, 30-second heartbeat, polling/dependency checks and disk. Rollouts verify a fresh heartbeat and logs. Historical metrics are timestamped; old cumulative counters are not current rates.','5 minutes':'Discuss blast radius, controlled service restart, cgroup events/PSI/swap/steal, sidecar pressure, readiness/liveness limits, timeout/cancellation, rollback, and evidence labels. The health endpoint can be green while an upload path fails. A historical 24-hour comparison had confounders and is not an SLO proof.','15 minutes':'Define user-job SLI and target, instrument phase latency and success by dependency, measure queue delay and cgroup pressure, specify alerts/runbook/rollback, and design a one-variable experiment. Explain current job loss on restart and how a durability objective would change architecture.'},
 'System-design interviewer':{'30 seconds':'I start from job semantics and workload, then bounded single-node processing fits the known constraints. I would not distribute until recovery, throughput or availability requirements exceed a measured one-node capacity.','2 minutes':'Clarify accepted sources, media/file size, burst rate, latency, job recovery, duplicate delivery and availability. Separate ingress, metadata, download, temporary storage and upload capacity. Start with an async bot, bounded workers, per-user fairness, local history and idempotency caveats. Measure which stage saturates before adding broker or nodes.','5 minutes':'Estimate jobs×bytes/time, compute burst arrival/service relationship with Little’s Law, bound RAM/disk by concurrent stage overlap, set timeouts and retry semantics, and specify queue durability. Identify Telegram/source quotas and ambiguous upload outcome.','15 minutes':'Explore vertical scaling, cautious worker increase, durable broker, shared DB/object storage and multiple nodes as triggered steps. For each, state new consistency, ownership, rate-limit, duplicate-execution and partition behavior; tie adoption to SLO and measured bottleneck.'},
 'Client':{'30 seconds':'It is a Telegram bot that downloads supported public media and returns it in chat, with guarded resource use and clear failure handling.','2 minutes':'A user sends a link, chooses a media format and receives the result. The service limits concurrent work, streams files instead of keeping full uploads in memory, and stores local history. Availability depends on Telegram and the source site.','5 minutes':'Explain source/site limitations, max file size, expected workflow, privacy of local state and what happens when a job is interrupted. Do not promise exact delivery or unsupported sources.','15 minutes':'Discuss functional scope, supported integrations, limits, operational support expectations, measured reliability data and future requirements before estimating schedule or scaling changes.'}};
  return <><SectionTitle eyebrow="PORTFOLIO & COMMUNICATION" title="Tell the engineering story" description="Adjust depth to the audience. Keep the factual core constant; do not exaggerate traffic or causal impact."/><div className="portfolio-controls"><label>Audience<select value={audience} onChange={e=>setAudience(e.target.value)}>{Object.keys(scripts).map(x=><option key={x}>{x}</option>)}</select></label><label>Length<select value={duration} onChange={e=>setDuration(e.target.value)}>{['30 seconds','2 minutes','5 minutes','15 minutes'].map(x=><option key={x}>{x}</option>)}</select></label></div><article className="portfolio-script"><div className="eyebrow">{audience.toUpperCase()} · {duration.toUpperCase()}</div><p>{scripts[audience][duration]}</p><div className="portfolio-points"><span><Badge>[C]</Badge> code/test facts</span><span><Badge>[M]</Badge> historical metrics</span><span><Badge>[R]</Badge> future triggers</span></div></article><div className="talk-track-grid">{['Why','Alternatives','Evidence','Trade-offs','Production verification','Scaling trigger'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><p>{['What user or resource problem did this solve?','What else could you choose and why not?','Which claim is measured versus code-derived?','What cost or limitation remains?','What test and live signal prove it works?','What measurable condition changes the architecture?'][i]}</p></div>)}</div><div className="callout"><b>Honest evidence</b><span>The 374acfd commit froze documentation; it did not change the application. Describe the application from v1.0.0 / 830f351.</span></div></>;
}
